version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.18.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Unit Tests
          command: node_modules/.bin/jest --ci --runInBand --coverage  && ./node_modules/.bin/codecov --token=$CODECOV_KEY
